// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNs5KcdDtzb9z0poumDDKFlhuSfiRfTU',
    appId: '1:431257189250:web:4a733110415b97b1942d9b',
    messagingSenderId: '431257189250',
    projectId: 'mymessenger-c0900',
    authDomain: 'mymessenger-c0900.firebaseapp.com',
    databaseURL: 'https://mymessenger-c0900-default-rtdb.firebaseio.com',
    storageBucket: 'mymessenger-c0900.appspot.com',
    measurementId: 'G-LXLG4EME8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlIaQcVRliAwfExVjwTC9dZ4kkcnaL5A',
    appId: '1:431257189250:android:d6b05a22e64b5936942d9b',
    messagingSenderId: '431257189250',
    projectId: 'mymessenger-c0900',
    databaseURL: 'https://mymessenger-c0900-default-rtdb.firebaseio.com',
    storageBucket: 'mymessenger-c0900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDf6LO3Od7bFs4ehnBOZITENPw4yXTGt4',
    appId: '1:431257189250:ios:e12bb4e4cffdc1ef942d9b',
    messagingSenderId: '431257189250',
    projectId: 'mymessenger-c0900',
    databaseURL: 'https://mymessenger-c0900-default-rtdb.firebaseio.com',
    storageBucket: 'mymessenger-c0900.appspot.com',
    iosClientId: '431257189250-mfjdqbj2ghqc93qvm40c093hct70n55e.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDf6LO3Od7bFs4ehnBOZITENPw4yXTGt4',
    appId: '1:431257189250:ios:c05049d59d5c1c6e942d9b',
    messagingSenderId: '431257189250',
    projectId: 'mymessenger-c0900',
    databaseURL: 'https://mymessenger-c0900-default-rtdb.firebaseio.com',
    storageBucket: 'mymessenger-c0900.appspot.com',
    iosClientId: '431257189250-ik1pbg8eehhehvaavpq4g1sju13s4dnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld.RunnerTests',
  );
}
